---
- name: Ensure that clamav-freshclam is not running in order to update the database
  systemd: state=stopped name=clamav-freshclam
  become: yes
  notify: "freshclam"
  tags:
    - security
    - clamav

- name: Start and enable the clamav service
  systemd: state=started name=clamav-daemon
  become: yes
  tags:
    - security
    - clamav

- name: Start and enable the freshclam service
  systemd: state=started name=clamav-freshclam
  become: yes
  tags:
    - security
    - clamav
