---
- name: Create a user profile
  user:
    name: pmonteiro-work
    password: '$6$njre9EVs$9BZugl5GcxpymEDI2hZxgxAJdW1FO1VQKfESjKPcZaCNhBMVy5MDzc9/iHS8pE7qeZ.S54J/xp1KucNbrFzPL0'
    groups:
     - docker
     - network
     - scanner
     - power
     - video
     - storage
     - wheel
    state: present
    shell: /bin/zsh
    system: no
    createhome: yes
    home: /home/pmonteiro-work
  become: yes
