---
- name: Install virtualization tools
  pacman:
    name: '{{ virtualization }}'
    state: present
  become: yes
  tags:
    - virtualization

- name: Check the Kernel Version with UNAME
  register: kernelVersion
  shell: uname -r | awk -F. '{ print $1$2 }'
  changed_when: false
  tags:
    - virtualization

- name: Install the relevant virtualbox-host-modules
  pacman:
    name: linux{{ kernelVersion.stdout }}-virtualbox-host-modules
    state: present
  become: yes
  tags:
    - virtualization

- name: Add the vboxdrv module
  modprobe:
    name: vboxdrv
    state: present
  tags:
    - virtualization