---
- name: Update cache and upgrade
  pacman:
    update_cache: yes
    upgrade: yes
    upgrade_extra_args: "--noconfirm"
  become: yes
  tags:
    - pre

- name: Install Utils
  pacman:
    name: '{{ utils }}'
    state: present
  become: yes
  tags:
    - utils


- name: Install Utils from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ utils_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  tags:
    - aur

- include: ntp.yml
- include: pip.yml
- include: bash.yml
- include: snap.yml
- include: terminator.yml

- name: Creates Workspace directory
  file:
    path: /home/{{ user_name }}/Workspace
    state: directory
  become_user: '{{ user_name }}'
  become: yes
