---
- name: Install Developer Tools
  pacman:
    name: '{{ developer_stack }}'
    state: present
  become_user: 'root'
  become: yes
  tags:
    - dev-tools

- include: go.yml

- name: Install Developer Tools from Arch User Repository
  script: ../../../aur/install-aur.sh {{ item }}
  with_items: '{{ developer_stack_aur }}'
  register: install_result
  changed_when: install_result.rc == 0
  failed_when: install_result.rc != 0 and install_result.rc != 255
  become: yes
  tags:
    - dev-tools
    - aur

- include: nvm.yml
- include: docker-config.yml
- include: emacs-config.yml
